name = "Console"
description = "A console in beeware"
version = "0.0.1"
autoclose_loader = true
packages = [
    "/static/wheels/console-0.0.1-py3-none-any.whl",
    "/static/wheels/toga_core-0.3.0.dev39-py3-none-any.whl",
    "/static/wheels/toga_web-0.3.0.dev39-py3-none-any.whl",
    "/static/wheels/travertino-0.1.3-py3-none-any.whl",
]
