[tool.briefcase]
project_name = "Console"
bundle = "com.example.console"
version = "0.0.1"
url = "https://console.example.com/console"
license = "MIT license"
author = 'coolcoder613'
author_email = "coolcoder613@outlook.com"

[tool.briefcase.app.console]
formal_name = "Console"
description = "A console in beeware"
icon = "src/console/resources/console"
installer_icon = "src/console/resources/console"
installer_background = "src/console/resources/console"
sources = ['src/console']
requires = [
]


[tool.briefcase.app.console.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.console.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.console.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.console.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.console.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.console.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.console.android]
requires = [
    'toga-android>=0.3.0.dev38'
]
icon.square = "src/console/resources/console-square"
icon.round = "src/console/resources/console-round"

[tool.briefcase.app.console.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
